### ISSUE TITLE
Can't run with Vagrant/VirtualBox

### ISSUE THREAD

**Issue by felipebueno** [mempko/firestr#19] opened 2015-08-18 17:01 UTC
Hi, @mempko 

Loved firestr! I work on a similar project called Sneer :smile: 

I was trying it following the vagrant instructions but could not run firestr. Here's a screenshot of the error:

![screenshot from 2015-08-18 13 56 08](https://cloud.githubusercontent.com/assets/241271/9336756/a4af2e0e-45b1-11e5-9382-44f7ab2d6c15.png)

**Comment by mempko** [comment] 2015-08-18 22:11
Ah! Thanks for pointing this out, I will look at it today tonight ASAP. 

Just looked at Sneer. Looks great! you did the right thing in having a phone app. This is something I regret not doing early. Fortunately the code is portable enough to create one, though will require lots of work.

**Comment by felipebueno** [comment] 2015-08-18 22:37
I'd love to get Fire★ running on my Raspberry Pi. Do you know if it's possible the way things are right now?

**Comment by mempko** [comment] 2015-08-19 12:33
I looked at it last night and it worked with no issues. I wasn't able to recreate what you saw. I don't see anything obviously wrong with what you did. Is it possible for you to tar your build directory and send it to me?

After you tar it, do "vagrant destroy" and try again if you can. Thanks!

**Comment by mempko** [comment] 2015-08-19 12:35
In regards to Raspberry Pi, there is no reason it shouldn't compile and run on it. I don't have any x86 specific code. I have an old asus netbook which I use to test 32bit and there are no issues. 

If you manage to compile and package Rasberry Pi, I would love to publish the package on the website for others and really appreciate it!

**Comment by mempko** [comment] 2015-12-22 00:54
I have updated the vagrant configs and tested to make sure they work. am gong to close this pr. Please reopen if the issue isn't resolved.

**Closed by mempko** 2015-12-22 00:54 UTC
Labels: bug
